Development
Aravindan07/polish-ui pull request #1
Opened 2021-03-22 13:40 UTC by Aravindan07

2021-03-22 13:56 UTC, Jaynil1611 requested changes
- Using consistent colors across componets
- Padding around image in card
- Image size & name in stacked list
- Use darker shade for gray text
- In mobile view, when you click on link close
- Fix CSS classes BEM navigation

2021-03-23 07:38 UTC, sjsouvik requested changes
Hey Aravindan!

Amazing work Aravindan, site is mobile responsive as well.

You can try to implement active section for side bar.
Also, add a footer, it'll look great

2021-03-24 18:38 UTC, yogeshpendse requested changes
Demo PR

2021-03-24 18:38 UTC, yogeshpendse commented on index.js
> +	}
I'm giving a demo PR

2021-03-25 09:56 UTC, asyriac commented
1. There is an offset (the title of the section is not visible) on clicking any link in the sidebar. This is happening since the main section starts from the top of the viewport.

2021-03-25 10:17 UTC, Jaynil1611 approved these changes
You can merge the pull request. All changes have been accommodated.

2021-03-25 10:58 UTC, Aravindan07 commented
Merging PR from development to main

2021-03-25 10:58 UTC, merged

2021-03-28 14:27 UTC, khusharth commented
- BEM: E stands for element.
```
 <img
	class="avatar__medium margin-lr-medium"
	src="image-url"
	alt="Avatar"
/>
```
Here you should use modifier instead of the Element. : avatar--medium

- margin-lr-medium: -> mr4 ml4 
- The medium keyword might confuse the user.